# Generated by Django 4.2.16 on 2026-09-05 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('CALLING', 'Calling (In Progress)'), ('COMPLETED', 'Completed'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('FOLLOW_UP', 'Follow-up Required'), ('WRONG_NUMBER', 'Wrong Number'), ('SWITCHED_OFF', 'Phone Switched Off'), ('CALLBACK', 'Requested Callback')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_interested', models.BooleanField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField(db_index=True)),
                ('follow_up_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to=settings.AUTH_USER_MODEL)),
                ('call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='calling.calllog')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
                'ordering': ['follow_up_date', 'follow_up_time'],
                'indexes': [models.Index(fields=['assigned_to', 'follow_up_date', 'is_completed'], name='calling_fol_assigne_5e45ae_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['employee', 'started_at'], name='calling_cal_employe_e3720f_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['lead', 'started_at'], name='calling_cal_lead_id_8243a4_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['result', 'started_at'], name='calling_cal_result_3085ce_idx'),
        ),
    ]
