# Generated by Django 4.2.16 on 2026-09-05 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/excel/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('duplicate_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('error_details', models.JSONField(default=dict)),
                ('column_mapping', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excel Import',
                'verbose_name_plural': 'Excel Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('company', models.CharField(blank=True, db_index=True, max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('EXCEL', 'Excel Upload'), ('MANUAL', 'Manual Entry'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('COLD_CALL', 'Cold Call'), ('SOCIAL', 'Social Media'), ('EMAIL', 'Email Campaign'), ('OTHER', 'Other')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CALLING', 'Calling'), ('COMPLETED', 'Completed'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('FOLLOW_UP', 'Follow-up Required'), ('CONVERTED', 'Converted'), ('INVALID', 'Invalid')], db_index=True, default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('product_interest', models.CharField(blank=True, max_length=200)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('last_called_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('excel_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.excelimport')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='leads.lead')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='leads_lead_phone_709d42_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'assigned_to'], name='leads_lead_status_a53442_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'),
        ),
    ]
